(assert_return (invoke "all-with-single-argument-are-true") (i32.const 1))
(assert_return (invoke "binary-equal" (i32.const 1) (i32.const 1)) (i32.const 1))
(assert_return (invoke "binary-equal" (i32.const 0) (i32.const 1)) (i32.const 0))
(assert_return (invoke "binary-greater-than" (i32.const 1) (i32.const 0)) (i32.const 1))
(assert_return (invoke "binary-greater-than" (i32.const 0) (i32.const 1)) (i32.const 0))
(assert_return (invoke "binary-less-than" (i32.const 1) (i32.const 0)) (i32.const 0))
(assert_return (invoke "binary-less-than" (i32.const 0) (i32.const 1)) (i32.const 1))
(assert_return (invoke "more-than-two-params-true") (i32.const 1))
(assert_return (invoke "more-than-two-params-false") (i32.const 0))
